### ISSUE TITLE
模拟器正常，真机全是Unknown.

### ISSUE THREAD

**Issue by wangleiTT** [kisekied/HLDevice#2]
是不是从utsname.machine里拿不到真机设备号啊?

**Comment by kisekied** [comment]
更新代码的时候有一个地方写错了，正在改了，感谢反馈

**Comment by kisekied** [comment]
> 是不是从utsname.machine里拿不到真机设备号啊?

已经修复了该问题，pod版本号是1.1.1，感谢反馈
