### ISSUE TITLE
催更啦催更啦~作者快把iPhone 11系列加上吧~~~哈哈

### ISSUE THREAD

**Issue by wangleiTT** [kisekied/HLDevice#4]
跪求

**Comment by kisekied** [comment]
目前wiki上没有相关的 `identifier`, 所以先根据模拟器上的结果来做一下。

欢迎提交反馈

**Comment by wangleiTT** [comment]
Thank you!

**Comment by wangleiTT** [comment]
我在项目中根据你的SDK写了一个Extension，判断是不是一个全面屏Face ID的设备，如果觉得实用可以直接拿走加到你的SDK中哈哈

+ (BOOL)isAllFaceIDCapableDevices {
    if ([HLDevice currentDevice].deviceModel == HLDeviceModeliPhoneX ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPhoneXS ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPhoneXSMax ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPhoneXR ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPhone11 ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPhone11Pro ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPhone11ProMax ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPadPro9Inch ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPadPro12Inch ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPadPro12Inch2 ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPadPro10Inch ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPadPro11Inch ||
        [HLDevice currentDevice].deviceModel == HLDeviceModeliPadPro12Inch3) {
        return YES;
    }
    
    return NO;
}
